### FindMy Auth API Tests

@baseUrl = http://localhost:5000/api/auth
@prodctionUrl = https://findmy-server.onrender.com/api/auth

### 1. Register User
## use valid email for real results
POST {{prodctionUrl}}/register
Content-Type: application/json

{
  "studentId": "22182381",
  "email": "vkpinto1234@gamil.com",
  "name": "Victor Pinto",
  "password": "1234567890",
  "phoneNumber": "0112233445"
}

### 2. Verify OTP
# Replace 'token' with the token received from Register and 'otp' with the code from email
POST {{baseUrl}}/verify-otp
Content-Type: application/json

{
  "token": "",
  "otp": ""
}

### 3. Resend OTP
# Replace 'token' with the token received from Register
POST {{baseUrl}}/resend-otp
Content-Type: application/json

{
  "token": "token"
}

### 4. Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### 5. Forgot Password
POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
  "email": ""
}

### 6. Reset Password
# Replace 'token' with the token received from Forgot Password and 'otp' with the code from email
POST {{baseUrl}}/reset-password
Content-Type: application/json

{
  "token": "token",
  "otp": "",
  "newPassword": ""
}

### 7. Logout
# Replace 'token' with the token received from Login
POST {{baseUrl}}/logout
Content-Type: application/json
Authorization: Bearer token
