### FindMy Auth API Tests

@baseUrl = http://localhost:5000/api/auth

### 1. Register User
## use valid email for real results
POST {{baseUrl}}/register
Content-Type: application/json

{
  "studentId": "",
  "email": "",
  "name": "",
  "password": "",
  "phoneNumber": ""
}

### 2. Verify OTP
# Replace 'token' with the token received from Register and 'otp' with the code from email
POST {{baseUrl}}/verify-otp
Content-Type: application/json

{
  "token": "",
  "otp": ""
}

### 3. Resend OTP
# Replace 'token' with the token received from Register
POST {{baseUrl}}/resend-otp
Content-Type: application/json

{
  "token": "token"
}

### 4. Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### 5. Forgot Password
POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
  "email": ""
}

### 6. Reset Password
# Replace 'token' with the token received from Forgot Password and 'otp' with the code from email
POST {{baseUrl}}/reset-password
Content-Type: application/json

{
  "token": "token",
  "otp": "",
  "newPassword": ""
}
