import Chat from '../models/Chat.js';
import Message from '../models/Message.js';
import Notification from '../models/Notification.js';

// Get my chats
export const getMyChats = async (req, res) => {
  try {
    const chats = await Chat.find({
      $or: [{ participant1: req.user.id }, { participant2: req.user.id }]
    })
    .populate('participant1', 'name email profilePicture')
    .populate('participant2', 'name email profilePicture')
    .populate({
      path: 'claim',
      select: 'item',
      populate: { path: 'item', select: 'title images' }
    })
    .sort({ lastMessage: -1 });

    return res.status(200).json({
      message: "Chats retrieved successfully.",
      count: chats.length,
      chats
    });
  } catch (error) {
    console.error("Get chats error:", error);
    return res.status(500).json({ message: "Internal server error." });
  }
};

// Get chat messages
export const getChatMessages = async (req, res) => {
  try {
    const chatId = req.params.id;
    
    // Ensure chat exists and user is part of it
    const chat = await Chat.findById(chatId);
    if (!chat) return res.status(404).json({ message: "Chat not found." });

    if (chat.participant1.toString() !== req.user.id && chat.participant2.toString() !== req.user.id) {
       return res.status(403).json({ message: "Access denied." });
    }

    const messages = await Message.find({ chat: chatId }).sort({ createdAt: 1 });
    
    // Optionally mark messages as read
    await Message.updateMany(
      { chat: chatId, sender: { $ne: req.user.id }, read: false },
      { $set: { read: true } }
    );

    return res.status(200).json({
      message: "Messages retrieved.",
      messages
    });
  } catch (error) {
    console.error("Get messages error:", error);
    return res.status(500).json({ message: "Internal server error." });
  }
};

// Send message
export const sendMessage = async (req, res) => {
  try {
    const chatId = req.params.id;
    const { content } = req.body;

    if (!content) return res.status(400).json({ message: "Message content required." });

    const chat = await Chat.findById(chatId);
    if (!chat) return res.status(404).json({ message: "Chat not found." });

    if (chat.participant1.toString() !== req.user.id && chat.participant2.toString() !== req.user.id) {
       return res.status(403).json({ message: "Access denied." });
    }

    const message = await Message.create({
      chat: chatId,
      sender: req.user.id,
      content
    });

    // Update lastMessage on Chat
    chat.lastMessage = Date.now();
    await chat.save();

    // Determine recipient
    const recipientId = chat.participant1.toString() === req.user.id ? chat.participant2 : chat.participant1;

    // Create a notification for the recipient
    await Notification.create({
      user: recipientId,
      type: "message",
      title: "New Message",
      message: `You have a new message`
    });

    // Provide the newly created message to emit via websocket if we are passing it backward
    // or typically we'd emit inside the socket.io logic. 
    // Wait, the safest is to emit right here by attaching `io` to the app. We'll do it if req.io is available.
    if (req.io) {
       req.io.to(chatId.toString()).emit("newMessage", message);
    }

    return res.status(201).json({
      message: "Message sent.",
      data: message
    });
  } catch (error) {
    console.error("Send message error:", error);
    return res.status(500).json({ message: "Internal server error." });
  }
};

// Send image message
export const sendImageMessage = async (req, res) => {
  try {
    const chatId = req.params.id;
    const chat = await Chat.findById(chatId);
    if (!chat) return res.status(404).json({ message: "Chat not found." });
    
    if (chat.participant1.toString() !== req.user.id && chat.participant2.toString() !== req.user.id) {
       return res.status(403).json({ message: "Access denied." });
    }

    if (!req.file) {
      return res.status(400).json({ message: "Image is required." });
    }

    // req.file.path contains the cloudinary URL generated by multer-storage-cloudinary
    const imageUrl = req.file.path;
    const content = req.body.content || "Sent an image";

    const message = await Message.create({
      chat: chatId,
      sender: req.user.id,
      content: content,
      hasImage: true,
      imageUrl: imageUrl
    });

    chat.lastMessage = Date.now();
    await chat.save();

    if (req.io) {
       req.io.to(chatId.toString()).emit("newMessage", message);
    }

    return res.status(201).json({
      message: "Image sent.",
      data: message
    });
  } catch (error) {
    console.error("Send image message error:", error);
    return res.status(500).json({ message: "Internal server error." });
  }
};
